### ISSUE TITLE
clicking "read more" button on blog page jumps users to the comments

### ISSUE THREAD

**Issue by RyanMPierson** [getgrav/grav-theme-pinpress#1]
When you click the read more button on blog posts from the blog page the reader is taken to the bottom of the post's page where the comments are instead of landing at the top of the page so they can start reading the post.

**Comment by hexplor** [comment]
I think it's related to comments plugin: https://github.com/getgrav/grav-plugin-comments It automatically sets autofocus: true to "name" field.

**Comment by flaviocopes** [comment]
@hexplor maybe I should drop that, right?

**Comment by hexplor** [comment]
Yeah. I think it might actually work better. Right now "read more" button causes switching right to the comments. This is a little bit misleading because user doesn't see the actual post :)

**Comment by flaviocopes** [comment]
Update released for Comments :+1:
