### ISSUE TITLE
Bottom Pageing Links give Access error.

### ISSUE THREAD

**Issue by jacmgr** [getgrav/grav-theme-pinpress#13]
Fresh install of theme. Installed on XAMPP.
The paging menu at bottom of home page are 
`http://localhost/testfolder/pinpress/page:2`
`http://localhost/testfolder/pinpress/page:3` etc.....

These lead to error:
```
Access forbidden!
You don't have permission to access the requested object.   
It is either read-protected or not readable by the server.
If you think this is a server error, please contact the webmaster.
Error 403
```

However if I insert the home page `blog` folder name explicitly, the links work perfectly. i.e. these urls work:
`http://localhost/testfolder/pinpress/blog/page:2`
`http://localhost/testfolder/pinpress/blog/page:3` etc.....

I tried using the `;` instead of ':' but get 404 error.

Please advise.
UPDATE: I tried some other skeletons (notepad) and have exactly same problem.  So maybe this is not pinpress theme problem.  Any help much appreciated.

**Comment by jacmgr** [comment]
problem disappeared for me after I relocated and configured the home page for other reasons.  Everything working fine for me.

**Comment by flaviocopes** [comment]
I tried and I have no issues with a fresh skeleton.

XAMPP means Windows, right? In this case you need to configure the parameter separator to `;` instead of `:`. A 404 could then be caused by another thing, see learn.getgrav.org/troubleshooting/page-not-found
