### ISSUE TITLE
Subpages in Menu

### ISSUE THREAD

**Issue by oscon** [getgrav/grav-theme-pinpress#5]
Is there a possibility to display subpages in the menu?

**Comment by flaviocopes** [comment]
I didn't check it, but looking at the Twig file that creates the menu, it's possible. The subpages must be visible https://learn.getgrav.org/content/headers#visible.

**Comment by oscon** [comment]
Seems not working for me:
No "arrow down" is shown in menu for "04.single-page (Exaple Page)", although I add some new folders with a visible default.md in it
![2016-06-24 14_42_17-04 single-page](https://cloud.githubusercontent.com/assets/478932/16338069/7befb9f8-3a1a-11e6-99d8-d48606ceb15c.jpg)
![2016-06-24 14_45_17-e__xampp_htdocs_pinpress_user_pages_04 single-page_01 test_default md - notepad](https://cloud.githubusercontent.com/assets/478932/16338072/7f9eb0f4-3a1a-11e6-93bf-7ea167d8dfc3.jpg)

**Comment by flaviocopes** [comment]
Checked a bit deeper.

The answer is submenu is not implemented in this theme, but the original PinPress theme HTML code / design supports it, so I've pushed a commit (https://github.com/getgrav/grav-theme-pinpress/commit/a2f878ad2fe13e1722863d12947564082dec6fa4) to support this, you need to checkout/download from Github to use it.

In the theme configuration then enable the dropdown.

![screen shot 2016-06-24 at 15 14 19](https://cloud.githubusercontent.com/assets/11783388/16338664/6ad4fb3e-3a1e-11e6-89f1-61a4f69d969d.png)

**Comment by oscon** [comment]
It's perfect now!! Thanks a lot
