### ISSUE TITLE
Twig error after changing the sidebar page

### ISSUE THREAD

**Issue by tampe125** [getgrav/grav-theme-pinpress#6]
Downloaded the Skeleton package for the pinpress theme.
Only changed the **About** page (replaced the dummy name with my real one).
Tried to check the changes on frontend and I got this:

`400 - Template "sidebar/blog.html.twig" is not defined in "partials/sidebar.html.twig" at line 4.` 

Could it be related to this? https://github.com/getgrav/grav-plugin-admin/issues/707

**Comment by flaviocopes** [comment]
Yes that's almost 100% the problem. 

The theme needs a few fixes in order to be able to customize the sidebar via Admin.

**Comment by tampe125** [comment]
Do you think a new release will be published soon?
In the meanwhile is there any manual workaround to apply?

Il 14 nov 2016 5:38 PM, "Flavio Copes" notifications@github.com ha
scritto:

**Comment by flaviocopes** [comment]
The theme needs to change the twig templates structure as Admin does not allow having page templates in subfolders and it defaults to changing it to the first page blueprint it finds. 

Meanwhile you can edit those pages manually via filesystem, in this way, the page template will not be changed.

**Comment by vip3rousmango** [comment]
I am also experiencing this issue, is there a known fix or work around? I just setup Grav and edited the About page only to have this occur and I don't know how to revert back...

**Comment by hellquist** [comment]
Is there really no instructions on how to revert this error?
I have managed to port almost all my content from my old site to Grav and PinPress, and then I decided to update one word in the sidebar via the admin, and that completely crashed my site. No matter what I try it doesn't come back. Wherever I search I can't find a solution for this, other than "start again".

I was hoping for something like "yeah, the admin added 2 files over there and changed 3 lines in the following files, if you take those out you are back to normal again"...

**Comment by dcrobertson01** [comment]
Rename the file to about.md - whatever it is complaining about in the error message.

File should be at users/pages/sidebar/about/about.md

It will have been renamed something like about.blog.md out something. 

On phone, bit hard to check st the mo

**Comment by karibuTW** [comment]
Same error here.
No idea how to fix it (How to revert back + how to modify the about page...)

Any solution?

EDIT: Found.
I had to do, in templates/sidebar
cp about.html.twig blog.html.twig
Now I can update the page.
